# Generated by Django 2.1.5 on 2020-10-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=200, verbose_name='标题')),
                ('date', models.DateField(auto_now_add=True, help_text='发布时间', verbose_name='发布时间')),
                ('content', models.TextField(help_text='详情', verbose_name='内容')),
                ('cls', models.IntegerField(choices=[(0, '通知-重要通知'), (1, '通知-人事安排'), (2, '通知-工作动态'), (3, '文化-自然景观'), (4, '文化-好物推荐'), (5, '文化-体育文化'), (6, '文化-健康知识'), (7, '学术-专家观点'), (8, '学术-知识科普'), (9, '学术-学者论述'), (10, '学术-学术研究'), (11, '教育-培训资讯')], help_text='所属分类', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='基地名称', max_length=200, verbose_name='基地名称')),
                ('number', models.CharField(help_text='基地编号', max_length=300, verbose_name='基地编号')),
            ],
            options={
                'verbose_name': '基地',
                'verbose_name_plural': '基地',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='证书所有人', max_length=200, verbose_name='证书所有人')),
                ('cardNumber', models.CharField(blank=True, help_text='身份证号,为专业人才时不可以为空', max_length=200, null=True, verbose_name='身份证号,为专业人才时不可以为空')),
                ('cls', models.IntegerField(choices=[(0, '专业人才'), (1, '荣誉证书'), (2, '学术顾问'), (3, '行业专家')], help_text='证书属性', verbose_name='证书属性')),
            ],
            options={
                'verbose_name': '证书',
                'verbose_name_plural': '证书',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='课题名称', max_length=200, verbose_name='课题名称')),
                ('number', models.CharField(help_text='编号', max_length=300, verbose_name='编号')),
                ('status', models.BooleanField(choices=[(False, '立项'), (True, '结项')], default=False, help_text='状态', verbose_name='状态')),
            ],
            options={
                'verbose_name': '课题',
                'verbose_name_plural': '课题',
            },
        ),
    ]
